//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace prueva10.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public int Id_Factura { get; set; }
        public int Factura_NitProveedor { get; set; }
        public string Factura_NombreProveedor { get; set; }
        public string Factura_Categoria { get; set; }
        public Nullable<System.DateTime> Factura_Fecha { get; set; }
        public string Factura_TipoMoneda { get; set; }
        public Nullable<double> Factra_MontoTotal { get; set; }
        public string Factura_ruta { get; set; }
    }
}
